services:

  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - inception_network
    volumes:
      - ./web:/var/www/html  # Ensure WordPress files are available to Nginx
  
  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wp-php
    volumes:
      - ./web:/var/www/html  # WordPress files should be in the same folder





  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
    volumes:
      - mariadb:/data
    networks:
      - inception_network
    restart: on-failure

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      device: /home/sbellafr/inc/srcs/data
      o: bind

networks:
    inception_network:
        name: inception_network
        driver: bridge
